### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by gersanchez** [over-engineer/lottie-for-elementor#10]
I was trying to play this animation
https://assets8.lottiefiles.com/packages/lf20_69XX0O.json

but I don't see anything on my website, even in the editor, just nothing... 

someone can explain how is the process, some kind of tutorial. cause I upload my JSON file or the URL link and I dont see anything.

Thanks1

**Comment by over-engineer** [comment]
Hey @gersanchez,

1. **Save the JSON file** you’ve linked locally
2. **Drag and drop the “Lottie” widget**, under the “General” widgets category of Elementor Page Builder
3. Click the “+” icon to **add a new Data file**, under “Content” → “Animation”
4. **Upload the JSON file** you’ve saved previously
5. **Click “Insert Media”**

That’s all you have to do! Your animation will start playing 🎉 

![screenshot](https://user-images.githubusercontent.com/6157348/81023045-e0ae6780-8e77-11ea-84fe-21240da973a5.png)

Make sure you’ve enabled “Loop”, under “Animation Options”, if you want your animation to play continuously.

You can also watch [this video](https://youtu.be/LYTTMPNQQZQ?t=422) by WPCrafter, starting **at about the 7:00 minute mark**, which does a really good job at explaining the whole process:

[![How To Add Motion Animations To Your Website Using Lottie & Elementor](http://i3.ytimg.com/vi/LYTTMPNQQZQ/maxresdefault.jpg)](https://youtu.be/LYTTMPNQQZQ?t=422)

If you have any further questions, just ask! 😄
