### ISSUE TITLE
Location of the “Lottie” widget

### ISSUE THREAD

**Issue by esti12345** [over-engineer/lottie-for-elementor#11]
I downloaded the plugin, installed and started ...
But to date, you can't find the Wiggits plugin in Elementor ...
I need help !!
what can I do? Why is it not shown to me?

**Comment by over-engineer** [comment]
Hey @esti12345,

you’ll find the **“Lottie” widget** under the “General” widgets category of Elementor Page Builder, or by searching for “Lottie”.

You can also watch [this video](https://youtu.be/LYTTMPNQQZQ?t=422) by WPCrafter, starting **at about the 7:00 minute mark**.

I’m going to close this issue now. However, if you have any further questions, do not hesitate to ask! 😄
