### ISSUE TITLE
Lottie not working

### ISSUE THREAD

**Issue by ArifBA** [over-engineer/lottie-for-elementor#12]
Hi,

I downloaded the plugin, installed it, created lottie element and it worked fine on a local installation of Wordpress & Elementor. However when I tried the same this with my live site the animation does appear, either in design or on the webpage. I only see the Lottie widget. 
![image](https://user-images.githubusercontent.com/65131845/81508074-a3bff600-92f9-11ea-92ea-12a7d1c10b5c.png)
I've tried deactivating all my other plugins but it hasn't made a difference.

Any ideas?

**Comment by over-engineer** [comment]
Hey @MyloUK,

it could be something with the setup of your live WordPress installation. It’s hard to tell without looking into the actual website.

If possible, could you please share a link to your website so I can take a look?

If you don’t want to post it publicly here, feel free to email me at dev@over-engineer.com

**Comment by ArifBA** [comment]
Thanks I've send it over to you 👍

**Comment by over-engineer** [comment]
I had a look at your website and noticed there are some [Mixed Content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) issues.

Basically, when someone visits your website everything is served over HTTPS (i.e. the connection with of the client with your server is encrypted), but **there are some resources served over HTTP**. That’s why, even your homepage, (where you don’t use Animentor at all) is “Not Secure”.

If you open the “Console” (on Google Chrome, <kbd>CTRL</kbd> + <kbd>Shift</kbd> + <kbd>J</kbd> on Windows, or <kbd>CMD</kbd> + <kbd>Option</kbd> + <kbd>J</kbd> on macOS), you’ll see several of those “Mixed Content” warnings and/or errors.

On the page that loads Animentor, you’ll see errors like this:

>Mixed Content: The page at 'https://[REDACTED]' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://[REDACTED]/wp-content/uploads/2020/05/[REDACTED].json'. This request has been blocked; the content must be served over HTTPS.

(along with some warning about JPG files that must be server over HTTPS as well)

You just have to fix this issue and Animentor will work normally 😄 

---

Did you transition from HTTP to HTTPS recently? Make sure you have changed both **WordPress Address (URL)** and **Site Address (URL)**, under Settings → General (on your WordPress dashboard). You could also try the **Replace URL** feature of Elementor, under Elementor → Tools → Replace URL.

If the above don’t work for you, search the web! Here’s a guide on [How to Quickly Fix WordPress Mixed Content Warnings (HTTPS/SSL)](https://kinsta.com/blog/wordpress-mixed-content-warning/) (although, please note that I haven’t used all of the methods it describes).

**Comment by ArifBA** [comment]
Hi there, Great thanks that has solved the problem! I move to https shortly after I setup the site but just notice yesterday the wordpress-general-settings still showed the HTTP address but running the replace URL suggested below has resolved it. Thank you! 👍 MyloUK Sent from Mail for Windows 10 From: Konstantinos PappasSent: 11 May 2020 00:06To: over-engineer/animentorCc: MyloUK; MentionSubject: Re: [over-engineer/animentor] Lottie not working (#12) I had a look at your website and noticed there are some Mixed Content issues.Basically, when someone visits your website everything is served over HTTPS (i.e. the connection with of the client with your server is encrypted), but there are some resources served over HTTP. That’s why, even your homepage, (where you don’t use Animentor at all) is “Not Secure”.If you open the “Console” (on Google Chrome, CTRL + Shift + J on Windows, or CMD + Option + J on macOS), you’ll see several of those “Mixed Content” warnings and/or errors.On the page that loads Animentor, you’ll see errors like this:Mixed Content: The page at 'https://[REDACTED]' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://[REDACTED]/wp-content/uploads/2020/05/[REDACTED].json'. This request has been blocked; the content must be served over HTTPS.(along with some warning about JPG files that must be server over HTTPS as well)You just have to fix this issue and Animentor will work normally 😄Did you transition from HTTP to HTTPS recently? Make sure you have changed both WordPress Address (URL) and Site Address (URL), under Settings → General (on your WordPress dashboard). You could also try the Replace URL feature of Elementor, under Elementor → Tools → Replace URL.If the above don’t work for you, search the web! Here’s a guide on How to Quickly Fix WordPress Mixed Content Warnings (HTTPS/SSL) (although, please note that I haven’t used all of the methods it describes).—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by over-engineer** [comment]
Happy to help! 😄
