### ISSUE TITLE
Admin slow with multiple Lottie elements.

### ISSUE THREAD

**Issue by Right-Brain-Group** [over-engineer/lottie-for-elementor#14]
I’m having issue in backend when I add multiple Lottie elements to the template it slows elementor down tremendously. Any suggestions?

**Comment by over-engineer** [comment]
Hey @Right-Brain-Group,

I’m sorry for my very late reply.

Does that affect the overall performance of the website or is it only noticeable on Elementor’s edit mode?

**Comment by over-engineer** [comment]
Hello again!

It’s been a while since the last comment on this, so I’ll assume your questions have been answered.

I’m going to close this, but please don’t hesitate to reach out if you have any more questions 😄
