### ISSUE TITLE
Lottie Animation showing on editor but not displayed when page is published (Elementor)

### ISSUE THREAD

**Issue by Mash402** [over-engineer/lottie-for-elementor#15]
Hi there,
I added Animentor plugin to my WP. When I added lottie widget the animation is displayed normally as it should be in the editor screen only. However, when the page is published, it is not there.

I reset WP altogether because of this issue. Now, that I started off with a blank slate (without any plugins except for elementor and animentor), I don't really know why it is not working.

Thanks for helping me figure out what the problem is

**Comment by over-engineer** [comment]
Hello @Mash402,

I’m sorry for the late reply, could you please answer the following:

- Which version of Elementor you’re using
- Are you using Elementor Pro (and which version)
- Are there any errors on the console? (on Google Chrome, <kbd>CTRL</kbd> + <kbd>Shift</kbd> + <kbd>J</kbd> on Windows, or <kbd>CMD</kbd> + <kbd>Option</kbd> + <kbd>J</kbd> on macOS)

Also, if possible, could you please share a link to your website so I can investigate it in more depth?

If you don’t want to post it publicly here, feel free to email me at dev@over-engineer.com

**Comment by over-engineer** [comment]
Hello again!

It’s been a while since the last comment on this, so I’ll assume your questions have been answered.

I’m going to close this, but please don’t hesitate to reach out if you have any more questions 😄
