### ISSUE TITLE
Lottie plugin doesn't show up

### ISSUE THREAD

**Issue by chaostra** [over-engineer/lottie-for-elementor#17]
Not sure if it's conflicting with the latest version of elementor, the plugin doesn't work. Followed your guide, but nothing showed up.

**Comment by over-engineer** [comment]
Hey @chaostra,

I’m sorry for my late reply.

Yes, there seems to be a conflict with the “Lottie” widget of Elementor Pro 2.10.

There is already an issue (#16) about that, so I’m closing this one. Feel free to follow its progress there.
