### ISSUE TITLE
Animation not showing on mobile or published page

### ISSUE THREAD

**Issue by LingoPerfecto** [over-engineer/lottie-for-elementor#22]
Hello I am using Elementor (basic) and installed Animentor, then I uploaded two Lottie animation files. The files show in the editor and in the web browser but when viewed on a mobile or another web browser they do not appear! Website is www.lingoperfecto.com
Please help ...

**Comment by over-engineer** [comment]
Hey @LingoPerfecto,

all Lottie animations seem to be loading correctly, tested on both desktop and mobile (Chrome on macOS, and iOS Safari) when accessing your website via HTTPS (try [this link](https://www.lingoperfecto.com/))

You just have to fix your configuration to always serve your website via HTTPS and Animentor will work normally 😄
