### ISSUE TITLE
Mouse over on div

### ISSUE THREAD

**Issue by bopatynski** [over-engineer/lottie-for-elementor#5]
Hi, is there a way we can add animation on mouseover on a certain div/ CSS ID or class?

**Comment by over-engineer** [comment]
Hey @bopatynski,

I’m not sure I understand what you mean by that.

You can configure each “Lottie” widget you’ve added with Animentor individually. If you need to play an animation on mouse over, you just have to **disable “Autoplay” and enable “Play on mouse over”**.

![screenshot](https://github.com/over-engineer/animentor/blob/master/assets/screenshot-2.png?raw=true)

If you need to _manually_ control an animation, I guess you could write some JavaScript to call `lottie.play()`, passing your animation name.

All Animentor widgets have the `.animentor-lottie-widget` class (you can always add your own from Elementor), so you could use that to target them. All widgets have a unique animation name stored as a data attribute (`data-name`).

You can `.play()` a specific animation:

```javascript
lottie.play('animentor-lottie-anim-xxxxxxx');
// where 'animentor-lottie-anim-xxxxxxx' is the animation name
```

You can print all animation names:

```javascript
document.querySelectorAll('.animentor-lottie-widget').forEach((widget) => {
  console.log(widget.getAttribute('data-name'));
});
```

You can listen for the [`mouseover`](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseover_event) event to do something when the mouse is over a widget:

```javascript
document.querySelector('#yourWidgetId').addEventListener('mouseover', (e) => {
  // Run some custom code
});
```

Lottie has several global methods that will affect all animations. A few examples:

- `lottie.goToAndStop()`
- `lottie.pause()`
- `lottie.play()`
- `lottie.setDirection()`
- `lottie.setSpeed()`
- `lottie.stop()`

Open DevTools, select the “Console” tab, and run `lottie;` to get all available methods. Or, look into the [lottie-web documentation](https://github.com/airbnb/lottie-web#lottie-has-several-global-methods-that-will-affect-all-animations).

Does this answer your question?

**Comment by over-engineer** [comment]
Hello again!

It’s been a while since the last comment on this, so I’ll assume your questions have been answered.

I’m going to close this, but please don’t hesitate to reach out if you have any more questions 😄
